# Dockerfile (backend Java)
FROM eclipse-temurin:17-jdk as builder
WORKDIR /app
COPY . .
RUN ls -la && ./mvnw clean package -DskipTests

FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
